In [1]:
!pip install nba-api

Collecting nba-api
  Downloading nba_api-1.10.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba-api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba-api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba-api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba-api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba-api) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba-api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba-api) (2025.8.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba-api) (1.17.0)
Downloading nba_api-1.10.1-py3-none-any.whl (285 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.3/285.3 kB 6.6 MB/s eta 0:00:00
Installing collected packages: nba-api
Successfully installed nba-api-1.10.1

In [2]:
import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguestandings

In [8]:
standings = pd.read_csv('data_all_teams_23-24_season.csv')

In [9]:
type(standings)

pandas.core.frame.DataFrame

In [13]:
standings.head()

,Unnamed: 0,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,ConferenceRecord,PlayoffRank,ClinchIndicator,...,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,PreAS,PostAS
0,0,0,22023,1610612760,Oklahoma City,Thunder,West,36-16,1,- w,...,NaN,NaN,NaN,NaN,NaN,3-1,9-5,10-3,37-17,20-8
1,1,0,22023,1610612738,Boston,Celtics,East,41-11,1,- e,...,NaN,NaN,NaN,NaN,NaN,3-0,11-4,12-2,43-12,21-6
2,2,0,22023,1610612752,New York,Knicks,East,35-17,2,- x,...,NaN,NaN,NaN,NaN,NaN,2-2,9-5,6-8,33-22,17-10
3,3,0,22023,1610612743,Denver,Nuggets,West,33-19,2,- x,...,NaN,NaN,NaN,NaN,NaN,4-0,9-6,10-5,36-19,21-6
4,4,0,22023,1610612750,Minnesota,Timberwolves,West,37-15,3,- x,...,NaN,NaN,NaN,NaN,NaN,1-2,13-2,10-3,39-16,17-10

In [11]:
standings.describe()

,Unnamed: 0,LeagueID,SeasonID,TeamID,PlayoffRank,DivisionRank,WINS,LOSSES,WinPCT,LeagueRank,...,EliminatedConference,EliminatedDivision,PointsPG,OppPointsPG,DiffPointsPG,May,Jun,Jul,Aug,Sep
count,30.000000,30.0,30.0,3.000000e+01,30.000000,30.00000,30.000000,30.000000,30.00000,8.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,0.0,0.0,0.0,0.0,0.0
mean,14.500000,0.0,22023.0,1.610613e+09,8.000000,3.00000,41.000000,41.000000,0.50000,2.500000,...,0.333333,0.333333,114.233333,114.233333,0.033333,NaN,NaN,NaN,NaN,NaN
std,8.803408,0.0,0.0,8.803408e+00,4.394354,1.43839,13.411266,13.411266,0.16355,1.195229,...,0.479463,0.479463,4.288584,4.368250,5.416981,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.0,22023.0,1.610613e+09,1.000000,1.00000,14.000000,18.000000,0.17100,1.000000,...,0.000000,0.000000,106.000000,107.000000,-10.000000,NaN,NaN,NaN,NaN,NaN
25%,7.250000,0.0,22023.0,1.610613e+09,4.250000,2.00000,31.250000,33.000000,0.38100,1.750000,...,0.000000,0.000000,112.000000,111.250000,-4.500000,NaN,NaN,NaN,NaN,NaN
50%,14.500000,0.0,22023.0,1.610613e+09,8.000000,3.00000,46.500000,35.500000,0.56700,2.500000,...,0.000000,0.000000,114.500000,113.500000,2.000000,NaN,NaN,NaN,NaN,NaN
75%,21.750000,0.0,22023.0,1.610613e+09,11.750000,4.00000,49.000000,50.750000,0.59800,3.250000,...,1.000000,1.000000,117.750000,117.000000,3.000000,NaN,NaN,NaN,NaN,NaN
max,29.000000,0.0,22023.0,1.610613e+09,15.000000,5.00000,64.000000,68.000000,0.78000,4.000000,...,1.000000,1.000000,123.000000,123.000000,11.000000,NaN,NaN,NaN,NaN,NaN

In [12]:
standings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 82 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               30 non-null     int64
 1   LeagueID                 30 non-null     int64
 2   SeasonID                 30 non-null     int64
 3   TeamID                   30 non-null     int64
 4   TeamCity                 30 non-null     object
 5   TeamName                 30 non-null     object
 6   Conference               30 non-null     object
 7   ConferenceRecord         30 non-null     object
 8   PlayoffRank              30 non-null     int64
 9   ClinchIndicator          22 non-null     object
 10  Division                 30 non-null     object
 11  DivisionRecord           30 non-null     object
 12  DivisionRank             30 non-null     int64
 13  WINS                     30 non-null     int64
 14  LOSSES                   30 non-null     int64
 15  WinPCT                   30 non-null     float64
 16  LeagueRank               8 non-null      float64
 17  Record                   30 non-null     object
 18  HOME                     30 non-null     object
 19  ROAD                     30 non-null     object
 20  L10                      30 non-null     object
 21  Last10Home               30 non-null     object
 22  Last10Road               30 non-null     object
 23  OT                       30 non-null     object
 24  ThreePTSOrLess           30 non-null     object
 25  TenPTSOrMore             30 non-null     object
 26  LongHomeStreak           30 non-null     int64
 27  strLongHomeStreak        30 non-null     object
 28  LongRoadStreak           30 non-null     int64
 29  strLongRoadStreak        30 non-null     object
 30  LongWinStreak            30 non-null     int64
 31  LongLossStreak           30 non-null     int64
 32  CurrentHomeStreak        30 non-null     int64
 33  strCurrentHomeStreak     30 non-null     object
 34  CurrentRoadStreak        30 non-null     int64
 35  strCurrentRoadStreak     30 non-null     object
 36  CurrentStreak            30 non-null     int64
 37  strCurrentStreak         30 non-null     object
 38  ConferenceGamesBack      30 non-null     float64
 39  DivisionGamesBack        30 non-null     float64
 40  ClinchedConferenceTitle  30 non-null     int64
 41  ClinchedDivisionTitle    30 non-null     int64
 42  ClinchedPlayoffBirth     30 non-null     int64
 43  EliminatedConference     30 non-null     int64
 44  EliminatedDivision       30 non-null     int64
 45  AheadAtHalf              30 non-null     object
 46  BehindAtHalf             30 non-null     object
 47  TiedAtHalf               30 non-null     object
 48  AheadAtThird             30 non-null     object
 49  BehindAtThird            30 non-null     object
 50  TiedAtThird              30 non-null     object
 51  Score100PTS              30 non-null     object
 52  OppScore100PTS           30 non-null     object
 53  OppOver500               30 non-null     object
 54  LeadInFGPCT              30 non-null     object
 55  LeadInReb                30 non-null     object
 56  FewerTurnovers           30 non-null     object
 57  PointsPG                 30 non-null     float64
 58  OppPointsPG              30 non-null     float64
 59  DiffPointsPG             30 non-null     float64
 60  vsEast                   30 non-null     object
 61  vsAtlantic               30 non-null     object
 62  vsCentral                30 non-null     object
 63  vsSoutheast              30 non-null     object
 64  vsWest                   30 non-null     object
 65  vsNorthwest              30 non-null     object
 66  vsPacific                30 non-null     object
 67  vsSouthwest              30 non-null     object
 68  Jan                      30 non-null     object
 69  Feb                      30 non-null     object
 70  Mar                      30 non-null     object
 71  Apr                      30 non-null     object
 72  May                      0 non-null      float64
 73  Jun                      0 non-null      float64
 74  Jul                      0 non-null      float64
 75  Aug                      0 non-null      float64
 76  Sep                      0 non-null      float64
 77  Oct                      30 non-null     object
 78  Nov                      30 non-null     object
 79  Dec                      30 non-null     object
 80  PreAS                    30 non-null     object
 81  PostAS                   30 non-null     object
dtypes: float64(12), int64(20), object(50)
memory usage: 19.3+ KB

In [ ]:
pd.reset_option('display.max_columns',None)

In [34]:
pd.reset_option('display.max_columns')

In [15]:
standings.head()

,Unnamed: 0,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,ConferenceRecord,PlayoffRank,ClinchIndicator,Division,DivisionRecord,DivisionRank,WINS,LOSSES,WinPCT,LeagueRank,Record,HOME,ROAD,L10,Last10Home,Last10Road,OT,ThreePTSOrLess,TenPTSOrMore,LongHomeStreak,strLongHomeStreak,LongRoadStreak,strLongRoadStreak,LongWinStreak,LongLossStreak,CurrentHomeStreak,strCurrentHomeStreak,CurrentRoadStreak,strCurrentRoadStreak,CurrentStreak,strCurrentStreak,ConferenceGamesBack,DivisionGamesBack,ClinchedConferenceTitle,ClinchedDivisionTitle,ClinchedPlayoffBirth,EliminatedConference,EliminatedDivision,AheadAtHalf,BehindAtHalf,TiedAtHalf,AheadAtThird,BehindAtThird,TiedAtThird,Score100PTS,OppScore100PTS,OppOver500,LeadInFGPCT,LeadInReb,FewerTurnovers,PointsPG,OppPointsPG,DiffPointsPG,vsEast,vsAtlantic,vsCentral,vsSoutheast,vsWest,vsNorthwest,vsPacific,vsSouthwest,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,PreAS,PostAS
0,0,0,22023,1610612760,Oklahoma City,Thunder,West,36-16,1,- w,Northwest,12-4,1,57,25,0.695,NaN,57-25,33-8,24-17,7-3,8-2,6-4,3-1,6-3,32-10,9,W 9,4,W 4,6,3,5,W 5,1,W 1,5,W 5,0.0,0.0,1,1,1,0,0,44-5,13-19,0-1,50-4,7-20,0-1,57-22,45-25,31-17,51-6,26-2,40-15,120.0,113.0,7.0,21-9,6-4,6-4,9-1,36-16,12-4,11-7,13-5,11-6,8-3,11-4,5-3,NaN,NaN,NaN,NaN,NaN,3-1,9-5,10-3,37-17,20-8
1,1,0,22023,1610612738,Boston,Celtics,East,41-11,1,- e,Atlantic,15-2,1,64,18,0.780,3.0,64-18,37-4,27-14,7-3,9-1,7-3,2-4,6-7,42-5,20,W 20,8,W 8,11,2,2,W 2,-1,L 1,2,W 2,0.0,0.0,1,1,1,0,0,56-11,8-7,0-0,59-6,4-12,1-0,64-15,49-18,38-13,56-2,43-6,31-9,121.0,109.0,11.0,41-11,15-2,13-5,13-4,23-7,6-4,7-3,10-0,11-5,9-1,12-4,6-2,NaN,NaN,NaN,NaN,NaN,3-0,11-4,12-2,43-12,21-6
2,2,0,22023,1610612752,New York,Knicks,East,35-17,2,- x,Atlantic,12-5,2,50,32,0.610,4.0,50-32,27-14,23-18,6-4,7-3,6-4,1-1,4-3,32-16,7,W 7,5,W 5,9,4,3,W 3,3,W 3,5,W 5,14.0,14.0,0,0,1,0,0,37-3,11-28,2-1,42-3,6-29,2-0,48-24,31-28,22-26,39-1,44-17,24-14,113.0,108.0,5.0,35-17,12-5,11-7,12-5,15-15,5-5,6-4,4-6,14-2,4-8,9-5,6-2,NaN,NaN,NaN,NaN,NaN,2-2,9-5,6-8,33-22,17-10
3,3,0,22023,1610612743,Denver,Nuggets,West,33-19,2,- x,Northwest,10-6,2,57,25,0.695,NaN,57-25,33-8,24-17,6-4,8-2,7-3,0-1,6-6,28-10,9,W 9,6,W 6,6,3,4,W 4,1,W 1,1,W 1,0.0,0.0,0,0,1,0,0,43-8,11-16,3-1,49-8,6-17,2-0,57-17,50-25,27-20,54-5,36-7,26-9,115.0,110.0,5.0,24-6,8-2,8-2,8-2,33-19,10-6,11-7,12-6,10-5,8-3,11-4,5-2,NaN,NaN,NaN,NaN,NaN,4-0,9-6,10-5,36-19,21-6
4,4,0,22023,1610612750,Minnesota,Timberwolves,West,37-15,3,- x,Northwest,12-4,3,56,26,0.683,NaN,56-26,30-11,26-15,6-4,7-3,6-4,1-4,7-6,32-10,7,W 7,5,W 5,7,2,-1,L 1,-1,L 1,-1,L 1,1.0,1.0,0,0,1,0,0,38-7,17-19,1-0,45-10,7-15,4-1,55-22,36-23,31-20,50-6,38-12,26-8,113.0,107.0,6.0,19-11,6-4,6-4,7-3,37-15,12-4,10-7,15-4,10-7,8-3,9-6,5-3,NaN,NaN,NaN,NaN,NaN,1-2,13-2,10-3,39-16,17-10

In [30]:
#Informações de desempenho geral, abaixo há uma descrição do que é cada atributo e abaixo disso o DataFrame que contém esses atributos
'''
W = vitórias
L = derrotas
W_PCT = porcentagem de vitórias

DivisionRank = posição do time na divisão
HOME = desempenho em casa (vitórias e derrotas)
ROAD = desempenho fora de casa (vitórias e derrotas)

ThreePTSOrLess = jogos decididos por 3 pontos ou menos
TenPTSOrMore = jogos com diferença de 10 ou mais pontos
LongWinStreak = maior sequência de vitórias
LongLossStreak = maior sequência de derrotas
PointsPG = média de pontos marcados por jogo
OppPointsPG = média de pontos sofridos por jogo
DiffPointsPG = diferença média entre pontos marcados e sofridos por jogo

vsEast = desempenho contra times da Conferência Leste
vsAtlantic = desempenho contra times da Divisão Atlantic
vsCentral = desempenho contra times da Divisão Central
vsSoutheast = desempenho contra times da Divisão Southeast
vsWest = desempenho contra times da Conferência Oeste
vsNorthwest = desempenho contra times da Divisão Northwest
vsPacific = desempenho contra times da Divisão Pacific
vsSouthwest = desempenho contra times da Divisão Southwest

Jan = desempenho nos jogos de janeiro
Feb = desempenho nos jogos de fevereiro
Mar = desempenho nos jogos de março
Apr = desempenho nos jogos de abril
May = desempenho nos jogos de maio
Jun = desempenho nos jogos de junho
Jul = desempenho nos jogos de julho
Aug = desempenho nos jogos de agosto
Sep = desempenho nos jogos de setembro
Oct = desempenho nos jogos de outubro
Nov = desempenho nos jogos de novembro
Dec = desempenho nos jogos de dezembro
'''

performance_standings = pd.DataFrame()
performance_standings = standings[['WINS','LOSSES','WinPCT','DivisionRank','HOME','ROAD','ThreePTSOrLess','TenPTSOrMore','LongWinStreak','LongLossStreak','PointsPG','OppPointsPG','DiffPointsPG','vsEast','vsAtlantic','vsCentral','vsSoutheast','vsWest','vsNorthwest','vsPacific','vsSouthwest','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']]
performance_standings.head()

,WINS,LOSSES,WinPCT,DivisionRank,HOME,ROAD,ThreePTSOrLess,TenPTSOrMore,LongWinStreak,LongLossStreak,PointsPG,OppPointsPG,DiffPointsPG,vsEast,vsAtlantic,vsCentral,vsSoutheast,vsWest,vsNorthwest,vsPacific,vsSouthwest,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,57,25,0.695,1,33-8,24-17,6-3,32-10,6,3,120.0,113.0,7.0,21-9,6-4,6-4,9-1,36-16,12-4,11-7,13-5,11-6,8-3,11-4,5-3,NaN,NaN,NaN,NaN,NaN,3-1,9-5,10-3
1,64,18,0.780,1,37-4,27-14,6-7,42-5,11,2,121.0,109.0,11.0,41-11,15-2,13-5,13-4,23-7,6-4,7-3,10-0,11-5,9-1,12-4,6-2,NaN,NaN,NaN,NaN,NaN,3-0,11-4,12-2
2,50,32,0.610,2,27-14,23-18,4-3,32-16,9,4,113.0,108.0,5.0,35-17,12-5,11-7,12-5,15-15,5-5,6-4,4-6,14-2,4-8,9-5,6-2,NaN,NaN,NaN,NaN,NaN,2-2,9-5,6-8
3,57,25,0.695,2,33-8,24-17,6-6,28-10,6,3,115.0,110.0,5.0,24-6,8-2,8-2,8-2,33-19,10-6,11-7,12-6,10-5,8-3,11-4,5-2,NaN,NaN,NaN,NaN,NaN,4-0,9-6,10-5
4,56,26,0.683,3,30-11,26-15,7-6,32-10,7,2,113.0,107.0,6.0,19-11,6-4,6-4,7-3,37-15,12-4,10-7,15-4,10-7,8-3,9-6,5-3,NaN,NaN,NaN,NaN,NaN,1-2,13-2,10-3

In [25]:
#Informações importantes de referência
reference_standings = pd.DataFrame()
reference_standings = standings[['LeagueID','SeasonID','TeamID','TeamCity','TeamName','Conference','Division']]
reference_standings.head()

,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,Division
0,0,22023,1610612760,Oklahoma City,Thunder,West,Northwest
1,0,22023,1610612738,Boston,Celtics,East,Atlantic
2,0,22023,1610612752,New York,Knicks,East,Atlantic
3,0,22023,1610612743,Denver,Nuggets,West,Northwest
4,0,22023,1610612750,Minnesota,Timberwolves,West,Northwest

In [33]:
clean_standings = pd.concat([reference_standings,performance_standings],axis=1)
clean_standings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   LeagueID        30 non-null     int64
 1   SeasonID        30 non-null     int64
 2   TeamID          30 non-null     int64
 3   TeamCity        30 non-null     object
 4   TeamName        30 non-null     object
 5   Conference      30 non-null     object
 6   Division        30 non-null     object
 7   WINS            30 non-null     int64
 8   LOSSES          30 non-null     int64
 9   WinPCT          30 non-null     float64
 10  DivisionRank    30 non-null     int64
 11  HOME            30 non-null     object
 12  ROAD            30 non-null     object
 13  ThreePTSOrLess  30 non-null     object
 14  TenPTSOrMore    30 non-null     object
 15  LongWinStreak   30 non-null     int64
 16  LongLossStreak  30 non-null     int64
 17  PointsPG        30 non-null     float64
 18  OppPointsPG     30 non-null     float64
 19  DiffPointsPG    30 non-null     float64
 20  vsEast          30 non-null     object
 21  vsAtlantic      30 non-null     object
 22  vsCentral       30 non-null     object
 23  vsSoutheast     30 non-null     object
 24  vsWest          30 non-null     object
 25  vsNorthwest     30 non-null     object
 26  vsPacific       30 non-null     object
 27  vsSouthwest     30 non-null     object
 28  Jan             30 non-null     object
 29  Feb             30 non-null     object
 30  Mar             30 non-null     object
 31  Apr             30 non-null     object
 32  May             0 non-null      float64
 33  Jun             0 non-null      float64
 34  Jul             0 non-null      float64
 35  Aug             0 non-null      float64
 36  Sep             0 non-null      float64
 37  Oct             30 non-null     object
 38  Nov             30 non-null     object
 39  Dec             30 non-null     object
dtypes: float64(9), int64(8), object(23)
memory usage: 9.5+ KB

In [35]:
clean_standings.head()

,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,Division,WINS,LOSSES,WinPCT,...,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,0,22023,1610612760,Oklahoma City,Thunder,West,Northwest,57,25,0.695,...,11-4,5-3,NaN,NaN,NaN,NaN,NaN,3-1,9-5,10-3
1,0,22023,1610612738,Boston,Celtics,East,Atlantic,64,18,0.780,...,12-4,6-2,NaN,NaN,NaN,NaN,NaN,3-0,11-4,12-2
2,0,22023,1610612752,New York,Knicks,East,Atlantic,50,32,0.610,...,9-5,6-2,NaN,NaN,NaN,NaN,NaN,2-2,9-5,6-8
3,0,22023,1610612743,Denver,Nuggets,West,Northwest,57,25,0.695,...,11-4,5-2,NaN,NaN,NaN,NaN,NaN,4-0,9-6,10-5
4,0,22023,1610612750,Minnesota,Timberwolves,West,Northwest,56,26,0.683,...,9-6,5-3,NaN,NaN,NaN,NaN,NaN,1-2,13-2,10-3